services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: invoice
      POSTGRES_PASSWORD: invoice_dev
      POSTGRES_DB: invoice_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  pgdata:
